languages:
  javascript:
    - eslint
  python:
    - pylint
    - ruff

exclude_patterns:
  - node_modules/
  - dist/
  - build/
  - "*.min.js"

eslint:
  config: .eslintrc.json

pylint:
  python-version: 3
