queue_rules:
  - name: Merge
    conditions:
      # Target the protected main branch
      - base=main
      # Require at least one approving review (aligns with common branch protection)
      - "#approved-reviews-by>=1"
      # Require that all mandatory CI checks have succeeded.
      # NOTE: These should correspond to the required status checks configured for main.
      # Add one `check-success=` entry per required check.
      - check-success=CI / validate
      - check-success=CI / unit-tests
      - check-success=CI / integration-tests
    batch_size: 1
    batch_max_wait_time: 0s
    merge_method: squash
    priority: high

pull_request_rules:
  - name: Add approved PRs with passing checks to Merge queue
    conditions:
      - base=main
      # Only auto-queue PRs explicitly marked for automation
      - label=automerge
      - "#approved-reviews-by>=1"
      # Ensure CI is green before enqueuing
      - check-success=CI / validate
      - check-success=CI / unit-tests
      - check-success=CI / integration-tests
    actions:
      queue:
        name: Merge
        method: squash
    # Main merge queue enforcing repository quality gates and branch protection policy
    merge_method: squash
    speculative_checks: 2
    batch_size: 5
    conditions:
      # Only protect main; add other protected branches here if needed (e.g., release/*)
      - base=main
      # Reviews: mirror branch protection (2 required approving reviews, no pending review requests)
      - '#approved-reviews-by>=2'
      - '#review-requested=0'
      - '#changes-requested-reviews-by=0'
      # Status / check runs representing repository quality gates
      - 'check-success=CI'
      - 'check-success=CodeQL'
      - 'check-success=Snyk'
      - 'check-success=Lint'
      - 'check-success=Smoke tests'
      # Ensure branch is clean and mergeable
      - 'conflict=FALSE'

pull_request_rules:
  # Queue PRs that meet branch protection and quality gate requirements
  - name: Add pull requests to Merge queue when all conditions are met
    conditions:
      - base=main
      # Opt-in labels for automated merging; adjust as needed
      - or:
          - label=automerge
          - label=dependencies
      # Reviews: align with .github/branch-protection.json (2 approvals, no pending or change-requested reviews)
      - '#approved-reviews-by>=2'
      - '#review-requested=0'
      - '#changes-requested-reviews-by=0'
      # All required checks / statuses must pass before queueing
      - 'check-success=CI'
      - 'check-success=CodeQL'
      - 'check-success=Snyk'
      - 'check-success=Lint'
      - 'check-success=Smoke tests'
      # Only mergeable, conflict-free PRs
      - 'conflict=FALSE'
    actions:
      queue:
        name: Merge
        method: squash
        update_method: merge
        # Use PR title and number for deterministic merge commit messages
        commit_message_template: |
          {{ title }} (#{{ number }})
