queue_rules:
  - name: Merge
    queue_conditions:
      # The following status checks must mirror .github/branch-protection.json
      - "check-success=Security Scan"
      - "check-success=CodeQL Analysis"
      - "check-success=Dependency Vulnerability Scan"
      - "check-success=Secret Scan (Gitleaks)"
      - "check-success=Static Application Security Testing"
      - "check-success=Lint / Code Quality"
      - "check-success=Unit Tests"
      - "check-success=Integration Tests"
      - "check-success=End-to-End Tests"
      - "check-success=Format Check"
      - "check-success=AI Code Review"
      - "check-success=AI Security Review"
      - "check-success=License Compliance"
      - "check-success=SBOM Generation"
      - "check-success=Build Validation"
      - "check-success=Docs Validation"
      - "check-success=Pre-commit Hooks"
      - "check-success=Cross-Platform CI (Linux)"
      - "check-success=Cross-Platform CI (macOS)"
      - "check-success=Cross-Platform CI (Windows)"
      - "check-success=Smoke Tests"
      - "check-success=Validation Workflow"
    conditions:
      # Target the protected main branch
      - base=main
      # Require at least one approving review (aligns with common branch protection)
      - "#approved-reviews-by>=1"
      # Require that all mandatory CI checks have succeeded.
      # NOTE: These should correspond to the required status checks configured for main.
      # Add one `check-success=` entry per required check.
      - check-success=CI / validate
      - check-success=CI / unit-tests
      - check-success=CI / integration-tests
    batch_size: 1
    batch_max_wait_time: 0s
    merge_method: squash
    priority: high

pull_request_rules:
  # Queue PRs that meet branch protection and quality gate requirements
  - name: Add pull requests to Merge queue when all conditions are met
    conditions:
      - base=main
      # Opt-in labels for automated merging; adjust as needed
      - or:
          - label=automerge
          - label=dependencies
      # Reviews: align with .github/branch-protection.json (2 approvals, no pending or change-requested reviews)
      - '#approved-reviews-by>=2'
      - '#review-requested=0'
      - '#changes-requested-reviews-by=0'
      # All required checks / statuses must pass before queueing
      - 'check-success=CI'
      - 'check-success=CodeQL'
      - 'check-success=Snyk'
      - 'check-success=Lint'
      - 'check-success=Smoke tests'
      # Only mergeable, conflict-free PRs
      - 'conflict=FALSE'
    actions:
      queue:
        name: Merge
        method: squash
        update_method: merge
        # Use PR title and number for deterministic merge commit messages
        commit_message_template: |
          {{ title }} (#{{ number }})
