#!/bin/bash
# GitHub Secrets Setup-Anleitung

echo "🔐 GitHub Actions Secrets einrichten"
echo ""
echo "Gehe zu: https://github.com/eyshoit-commits/setup/settings/secrets/actions"
echo ""
echo "Füge folgende Secrets hinzu:"
echo ""
echo "1. CODECOV_TOKEN"
echo "   Wert: <dein Codecov Token>"
echo ""
echo "2. WAKATIME_API_KEY"
echo "   Wert: <dein WakaTime API Key>"
echo ""
echo "3. GITHUB_TOKEN (optional, wird automatisch bereitgestellt)"
echo "   Hinweis: GITHUB_TOKEN wird automatisch von GitHub Actions bereitgestellt."
echo "   Nur nötig für erweiterte API-Zugriffe außerhalb von Actions."
echo ""
echo "📝 Optional (falls gewünscht):"
echo "4. SNYK_TOKEN - Für Snyk Security Scanning"
echo "5. CODACY_PROJECT_TOKEN - Für Codacy Integration"
echo ""
echo "✅ Nach dem Hinzufügen sind die Workflows vollständig funktionsfähig!"
